@startmindmap
*[#white] Target
**[#mediumaquamarine] <&flag> English
***_ mikan Word App
***_ Essential Grammar in Use
***_ Read the Sapiens
**[#skyblue] Tech_1: Social contribution
***_ DjangoGirls Repository
***_ Contributing to OSS
**[#plum] Tech_2: Deepen my knowledge
***_ Introduction to Lisp: For Emacs configuration
***_ Weekly Tech-Blog
***_ Writing & making books with technical content
**[#pink] Exercise
***_ Dog-walking🐶
***_ Trampoline♪
**[#orange] Creation
***_ Stained glass
@endmindmap
