@startmindmap
* 目標
**[#gold] Chrome 拡張
***_ cookie を使わずに text の保持するよう修正
**[#lightblue] GitHub
***_ todo を GitHubProjects で管理 => PlantUML でマインドマップ管理するので不要かも
***_ README 整備
**[#plum] emacs
***_ Org-mode 整備
***_ PlantUML でマインドマップ管理 (Org-mode と互換性あり)
***_ highlight-indentation-mode / indent-guide
***_ whitespace-mod
**[#lightgreen] RasPi
***_ 人感センサー&自動撮影
**[#FFBBCC] hugo
***_ スクリーンショットファイルを自動で SS-2020-07-11 19.52.47.png などになるよう設定
***_ ロゴ描いて可愛い感じにする
**[#silver] アドベントカレンダー
***_ WordPress → 静的サイトへ移行ネタで書く
@endmindmap
