@startmindmap
*[#white] 目標
**[#tomato] <&flag> 英会話
***_ mikan
***_ Daily英会話 (Online)
***_ Sapiens
**[#plum] Tech
***_ Emacs (Lisp 入門)
***_ Blog (週イチ)
**[#mistyrose] 軽運動
***_ ストレッチ
**[#deepskyblue] 創作
***_ ステンドグラス
@endmindmap
